### ISSUE TITLE
Проблемы с кодировкой

### ISSUE THREAD

**Issue by andrey-ilyin** [AnyaGl/Backend_labs#2]
https://github.com/AnyaGl/Backend_labs/blob/3bb2ea8aa16556601aa7fe2d924fbb22f2c01ba8/lab3/RemoveExtraBlanks/RemoveExtraBlanksTests/RemoveExtraBlanksTests.cs#L17

**Comment by AnyaGl** [comment]
> https://github.com/AnyaGl/Backend_labs/blob/3bb2ea8aa16556601aa7fe2d924fbb22f2c01ba8/lab3/RemoveExtraBlanks/RemoveExtraBlanksTests/RemoveExtraBlanksTests.cs#L17

Исправила. Хочу уточнить, PasswordStrength Вы не проверили, потому что в этом задании ошибка?

**Comment by andrey-ilyin** [comment]
Принято.
